# Generated by Django 3.2.dev20200618194320 on 2020-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=200)),
                ('Team_id', models.IntegerField()),
                ('Team_members', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
